In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('C:/Users/Sneha Reddy/OneDrive/Documents/AI-Project/Merged_Segmented_CSV.csv')

In [3]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [4]:
X

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  1,  0,  0],
       ...,
       [ 0,  0,  0, ..., 28, 16,  5],
       [ 0,  0,  0, ..., 38,  0,  1],
       [ 0,  0,  0, ..., 19,  0,  0]], dtype=int64)

In [5]:
y

array(['Normal', 'Normal', 'Normal', ..., 'Pneumonia', 'Pneumonia',
       'Pneumonia'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(7200, 625)

In [9]:
X_test.shape

(1800, 625)

In [10]:
y_train.shape

(7200,)

In [11]:
y_test.shape

(1800,)

In [12]:
X_train

array([[  0,   0,   0, ..., 165,   1,   4],
       [  0,   0,   0, ...,   1,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   2,   2,   4],
       [  0,   0,   0, ...,   1,   1,   1],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [13]:
X_test

array([[ 0,  0,  0, ...,  1,  1,  6],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 10,  1,  1],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  5,  8,  1],
       [ 0,  0,  0, ...,  2,  1,  0]], dtype=int64)

In [14]:
y_train

array(['Pneumonia', 'Normal', 'Other', ..., 'Other', 'Other', 'Normal'],
      dtype=object)

In [15]:
y_test

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [18]:
X_train

array([[-0.2280515 , -0.02495553, -0.04092578, ...,  4.41463923,
        -0.23525444, -0.0568118 ],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.31406133,
        -0.26317965, -0.23354325],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325],
       ...,
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.28522779,
        -0.20732922, -0.0568118 ],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.31406133,
        -0.23525444, -0.18936039],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325]])

In [19]:
X_test

array([[-0.2280515 , -0.02495553, -0.04092578, ..., -0.31406133,
        -0.23525444,  0.03155393],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.05455947,
        -0.23525444, -0.18936039],
       ...,
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.19872717,
        -0.03977792, -0.18936039],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.28522779,
        -0.23525444, -0.23354325]])

In [20]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [21]:
#Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [24]:
y_pred_logreg=logreg.predict(X_test)

In [25]:
y_pred_logreg

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [26]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[538,  39,  18],
       [ 54, 518,  25],
       [ 18,  37, 553]], dtype=int64)

In [27]:
accuracy_score(y_test, y_pred_logreg)

0.8938888888888888

In [28]:
precision_score(y_test, y_pred_logreg,average='weighted')

0.8941782675596444

In [29]:
recall_score(y_test, y_pred_logreg, average='weighted')

0.8938888888888888

In [30]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.8939551768697215

In [31]:
#Naive Bayes

In [32]:
from sklearn.naive_bayes import GaussianNB

In [33]:
nb = GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [34]:
y_pred_nb=nb.predict(X_test)

In [35]:
y_pred_nb

array(['Other', 'Normal', 'Pneumonia', ..., 'Normal', 'Pneumonia',
       'Normal'], dtype='<U9')

In [36]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[491,  73,  31],
       [250, 303,  44],
       [138,  42, 428]], dtype=int64)

In [37]:
accuracy_score(y_test, y_pred_nb)

0.6788888888888889

In [38]:
precision_score(y_test, y_pred_nb,average='weighted')

0.7124767566589197

In [39]:
recall_score(y_test, y_pred_nb, average='weighted')

0.6788888888888889

In [40]:
f1_score(y_test, y_pred_nb, average='weighted')

0.6784905948061168

In [41]:
#KNN

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [44]:
y_pred_knn=knn.predict(X_test)

In [45]:
y_pred_knn

array(['Other', 'Pneumonia', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [46]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[424, 142,  29],
       [113, 467,  17],
       [ 30,  37, 541]], dtype=int64)

In [47]:
accuracy_score(y_test, y_pred_knn)

0.7955555555555556

In [48]:
precision_score(y_test, y_pred_knn,average='weighted')

0.7982611195046672

In [49]:
recall_score(y_test, y_pred_knn, average='weighted')

0.7955555555555556

In [50]:
f1_score(y_test, y_pred_knn, average='weighted')

0.7962858262660474

In [51]:
#Decision Tree

In [52]:
from sklearn import tree

In [53]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train, y_train)

In [54]:
dt.tree_.node_count

531

In [55]:
dt.tree_.max_depth

23

In [56]:
y_pred_dt=dt.predict(X_test)

In [57]:
y_pred_dt

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [58]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[558,  25,  12],
       [ 31, 521,  45],
       [  4,  42, 562]], dtype=int64)

In [59]:
accuracy_score(y_test, y_pred_dt)

0.9116666666666666

In [60]:
precision_score(y_test, y_pred_dt,average='weighted')

0.9115940944567467

In [61]:
recall_score(y_test, y_pred_dt, average='weighted')

0.9116666666666666

In [62]:
f1_score(y_test, y_pred_dt, average='weighted')

0.911587806197908

In [83]:
#Random Forest

In [84]:
from sklearn.ensemble import RandomForestClassifier

In [85]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [86]:
y_pred_rf=rf.predict(X_test)

In [87]:
y_pred_rf

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [88]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[583,   8,   4],
       [ 19, 569,   9],
       [  0,  13, 595]], dtype=int64)

In [89]:
accuracy_score(y_test, y_pred_rf)

0.9705555555555555

In [90]:
precision_score(y_test, y_pred_rf,average='weighted')

0.9705398764945473

In [91]:
recall_score(y_test, y_pred_rf, average='weighted')

0.9705555555555555

In [92]:
f1_score(y_test, y_pred_rf, average='weighted')

0.970525645215413

In [93]:
#Support Vector Machine

In [94]:
from sklearn.svm import SVC

In [95]:
svm = SVC()
svm.fit(X_train, y_train)

SVC()

In [96]:
y_pred_svm=svm.predict(X_test)

In [97]:
y_pred_svm

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Normal'], dtype=object)

In [98]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[507,  80,   8],
       [ 68, 509,  20],
       [ 11,  10, 587]], dtype=int64)

In [99]:
accuracy_score(y_test, y_pred_svm)

0.8905555555555555

In [100]:
precision_score(y_test, y_pred_svm,average='weighted')

0.8902254941341731

In [101]:
recall_score(y_test, y_pred_svm, average='weighted')

0.8905555555555555

In [102]:
f1_score(y_test, y_pred_svm, average='weighted')

0.8903626295713752