In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('C:/Users/Sneha Reddy/OneDrive/Documents/AI-Project/Merged_CSV.csv')

In [3]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [4]:
X

array([[   0,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   2,    0,    0, ...,    1,    1,    0],
       ...,
       [8997,    0,    0, ...,    1,   28,   16],
       [8998,    0,    0, ...,   16,   38,    0],
       [8999,    0,    0, ...,    5,   19,    0]], dtype=int64)

In [5]:
y

array([0, 0, 0, ..., 5, 1, 0], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(7200, 625)

In [9]:
X_test.shape

(1800, 625)

In [10]:
y_train.shape

(7200,)

In [11]:
y_test.shape

(1800,)

In [12]:
X_train

array([[6157,    0,    0, ...,  218,  165,    1],
       [2923,    0,    0, ...,    2,    1,    0],
       [5155,    0,    0, ...,    1,    0,    0],
       ...,
       [4859,    0,    0, ...,    1,    2,    2],
       [3264,    0,    0, ...,    1,    1,    1],
       [2732,    0,    0, ...,    1,    0,    0]], dtype=int64)

In [13]:
X_test

array([[4424,    0,    0, ...,    1,    1,    1],
       [1726,    0,    0, ...,    1,    0,    0],
       [7895,    0,    0, ...,    8,   10,    1],
       ...,
       [7193,    0,    0, ...,    1,    0,    0],
       [6280,    0,    0, ...,    1,    5,    8],
       [4905,    0,    0, ...,    2,    2,    1]], dtype=int64)

In [14]:
y_train

array([4, 0, 0, ..., 4, 1, 0], dtype=int64)

In [15]:
y_test

array([6, 0, 1, ..., 0, 1, 0], dtype=int64)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [18]:
X_train

array([[ 0.64166305, -0.2280515 , -0.02495553, ...,  6.06473378,
         4.41463923, -0.23525444],
       [-0.60548323, -0.2280515 , -0.02495553, ..., -0.30870956,
        -0.31406133, -0.26317965],
       [ 0.25525595, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965],
       ...,
       [ 0.14110774, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.28522779, -0.20732922],
       [-0.47398141, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.31406133, -0.23525444],
       [-0.67913967, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965]])

In [19]:
X_test

array([[-0.02664385, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.31406133, -0.23525444],
       [-1.06708932, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965],
       [ 1.31189812, -0.2280515 , -0.02495553, ..., -0.13166947,
        -0.05455947, -0.23525444],
       ...,
       [ 1.04118177, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965],
       [ 0.68909626, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.19872717, -0.03977792],
       [ 0.15884699, -0.2280515 , -0.02495553, ..., -0.30870956,
        -0.28522779, -0.23525444]])

In [20]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [21]:
#Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [24]:
y_pred_logreg=logreg.predict(X_test)

In [25]:
y_pred_logreg

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[964,  71,  18, ...,   0,   0,   0],
       [193,  44,  13, ...,   0,   0,   0],
       [ 51,  24,  12, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [27]:
accuracy_score(y_test, y_pred_logreg)

0.575

In [28]:
precision_score(y_test, y_pred_logreg,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5050157703039403

In [29]:
recall_score(y_test, y_pred_logreg, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.575

In [30]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.5332322865088858

In [31]:
#Naive Bayes

In [32]:
from sklearn.naive_bayes import GaussianNB

In [33]:
nb = GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [34]:
y_pred_nb=nb.predict(X_test)

In [35]:
y_pred_nb

array([12,  0, 11, ..., 21, 18,  0], dtype=int64)

In [36]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[418,   5,  12, ...,   0,   0,   0],
       [ 69,   2,   4, ...,   0,   0,   0],
       [ 17,   4,   2, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [37]:
accuracy_score(y_test, y_pred_nb)

0.23777777777777778

In [38]:
precision_score(y_test, y_pred_nb,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5122515248802162

In [39]:
recall_score(y_test, y_pred_nb, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.23777777777777778

In [40]:
f1_score(y_test, y_pred_nb, average='weighted')

0.32079761391809625

In [41]:
#KNN

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [44]:
y_pred_knn=knn.predict(X_test)

In [45]:
y_pred_knn

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [46]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[961,  90,  20, ...,   0,   0,   0],
       [215,  57,   7, ...,   0,   0,   0],
       [ 62,  30,  10, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [47]:
accuracy_score(y_test, y_pred_knn)

0.5733333333333334

In [48]:
precision_score(y_test, y_pred_knn,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4660246252440834

In [49]:
recall_score(y_test, y_pred_knn, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5733333333333334

In [50]:
f1_score(y_test, y_pred_knn, average='weighted')

0.5097411580090287

In [51]:
#Decision Tree

In [52]:
from sklearn import tree

In [53]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train, y_train)

In [54]:
dt.tree_.node_count

2831

In [55]:
dt.tree_.max_depth

54

In [56]:
y_pred_dt=dt.predict(X_test)

In [57]:
y_pred_dt

array([10,  0,  0, ...,  0,  0,  0], dtype=int64)

In [58]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[884, 121,  30, ...,   0,   0,   0],
       [100, 115,  36, ...,   0,   0,   0],
       [ 26,  32,  21, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [59]:
accuracy_score(y_test, y_pred_dt)

0.5777777777777777

In [60]:
precision_score(y_test, y_pred_dt,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5897673171254258

In [61]:
recall_score(y_test, y_pred_dt, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5777777777777777

In [62]:
f1_score(y_test, y_pred_dt, average='weighted')

0.5829889512354005

In [63]:
#Random Forest

In [64]:
from sklearn.ensemble import RandomForestClassifier

In [65]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [66]:
y_pred_rf=rf.predict(X_test)

In [67]:
y_pred_rf

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [68]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[1062,   17,    2, ...,    0,    0,    0],
       [ 224,   59,    1, ...,    0,    0,    0],
       [  70,   30,    4, ...,    0,    0,    0],
       ...,
       [   1,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [69]:
accuracy_score(y_test, y_pred_rf)

0.6283333333333333

In [70]:
precision_score(y_test, y_pred_rf,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4903689085165121

In [71]:
recall_score(y_test, y_pred_rf, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6283333333333333

In [72]:
f1_score(y_test, y_pred_rf, average='weighted')

0.5361600315069022

In [73]:
#Support Vector Machine

In [74]:
from sklearn.svm import SVC

In [75]:
svm = SVC()
svm.fit(X_train, y_train)

SVC()

In [76]:
y_pred_svm=svm.predict(X_test)

In [77]:
y_pred_svm

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [78]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[1067,   13,    1, ...,    0,    0,    0],
       [ 266,   17,    0, ...,    0,    0,    0],
       [  99,    4,    2, ...,    0,    0,    0],
       ...,
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [79]:
accuracy_score(y_test, y_pred_svm)

0.6033333333333334

In [80]:
precision_score(y_test, y_pred_svm,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.44325746921877074

In [81]:
recall_score(y_test, y_pred_svm, average='weighted')

0.6033333333333334

In [82]:
f1_score(y_test, y_pred_svm, average='weighted')

0.47388748028504735