In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('C:/Users/Sneha Reddy/OneDrive/Documents/AI-Project/Merged_Segmented_CSV.csv')

In [3]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [4]:
X

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  1,  0,  0],
       ...,
       [ 0,  0,  0, ..., 28, 16,  5],
       [ 0,  0,  0, ..., 38,  0,  1],
       [ 0,  0,  0, ..., 19,  0,  0]], dtype=int64)

In [5]:
y

array(['Normal', 'Normal', 'Normal', ..., 'Pneumonia', 'Pneumonia',
       'Pneumonia'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(7200, 625)

In [9]:
X_test.shape

(1800, 625)

In [10]:
y_train.shape

(7200,)

In [11]:
y_test.shape

(1800,)

In [12]:
X_train

array([[  0,   0,   0, ..., 165,   1,   4],
       [  0,   0,   0, ...,   1,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   2,   2,   4],
       [  0,   0,   0, ...,   1,   1,   1],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [13]:
X_test

array([[ 0,  0,  0, ...,  1,  1,  6],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 10,  1,  1],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  5,  8,  1],
       [ 0,  0,  0, ...,  2,  1,  0]], dtype=int64)

In [14]:
y_train

array(['Pneumonia', 'Normal', 'Other', ..., 'Other', 'Other', 'Normal'],
      dtype=object)

In [15]:
y_test

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [16]:
#Feature Scaling
#Standardize the data
#X_std=(x-mean(x))/std_dev(x)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [19]:
X_train

array([[-0.2280515 , -0.02495553, -0.04092578, ...,  4.41463923,
        -0.23525444, -0.0568118 ],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.31406133,
        -0.26317965, -0.23354325],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325],
       ...,
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.28522779,
        -0.20732922, -0.0568118 ],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.31406133,
        -0.23525444, -0.18936039],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325]])

In [20]:
X_test

array([[-0.2280515 , -0.02495553, -0.04092578, ..., -0.31406133,
        -0.23525444,  0.03155393],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.05455947,
        -0.23525444, -0.18936039],
       ...,
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.19872717,
        -0.03977792, -0.18936039],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.28522779,
        -0.23525444, -0.23354325]])

In [21]:
#LDA for dimensionality reduction

In [22]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [23]:
lda=LDA(n_components=2)

In [24]:
X_train_lda=lda.fit_transform(X_train,y_train)
X_test_lda=lda.transform(X_test)

In [25]:
lda.n_components

2

In [26]:
X_train_lda

array([[ 4.0970027 , -1.26179694],
       [ 0.40034589,  0.44131747],
       [-0.98088051, -2.29763219],
       ...,
       [-2.16955824, -0.82913475],
       [-1.02543003, -2.59382072],
       [-1.93790833,  0.57770423]])

In [27]:
X_train_lda.shape

(7200, 2)

In [28]:
X_test_lda

array([[-1.49115486, -1.64806243],
       [ 0.51406625,  2.58614534],
       [ 4.14359979,  0.11518854],
       ...,
       [ 2.31241247,  0.56399883],
       [ 2.75796142, -0.60166586],
       [-1.15062552,  0.31005727]])

In [29]:
X_test_lda.shape

(1800, 2)

In [30]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [31]:
#Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
logreg = LogisticRegression()
logreg.fit(X_train_lda,y_train)

LogisticRegression()

In [34]:
y_pred_logreg=logreg.predict(X_test_lda)

In [35]:
y_pred_logreg

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Normal'], dtype=object)

In [36]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[479,  96,  20],
       [ 85, 488,  24],
       [ 27,  25, 556]], dtype=int64)

In [37]:
accuracy_score(y_test, y_pred_logreg)

0.8461111111111111

In [38]:
precision_score(y_test, y_pred_logreg,average='weighted')

0.8466886292008295

In [39]:
recall_score(y_test, y_pred_logreg, average='weighted')

0.8461111111111111

In [40]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.8463566178589771

In [41]:
#Naive Bayes

In [42]:
from sklearn.naive_bayes import GaussianNB

In [43]:
nb = GaussianNB()
nb.fit(X_train_lda,y_train)

GaussianNB()

In [44]:
y_pred_nb=nb.predict(X_test_lda)

In [45]:
y_pred_nb

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Normal'], dtype='<U9')

In [46]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[468, 105,  22],
       [ 78, 494,  25],
       [ 23,  25, 560]], dtype=int64)

In [47]:
accuracy_score(y_test, y_pred_nb)

0.8455555555555555

In [48]:
precision_score(y_test, y_pred_nb,average='weighted')

0.8460735865449853

In [49]:
recall_score(y_test, y_pred_nb, average='weighted')

0.8455555555555555

In [50]:
f1_score(y_test, y_pred_nb, average='weighted')

0.8455503781518799

In [51]:
#KNN

In [52]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_lda,y_train)

KNeighborsClassifier(n_neighbors=3)

In [54]:
y_pred_knn=knn.predict(X_test_lda)

In [55]:
y_pred_knn

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [56]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[456, 117,  22],
       [101, 474,  22],
       [ 33,  34, 541]], dtype=int64)

In [57]:
accuracy_score(y_test, y_pred_knn)

0.8172222222222222

In [58]:
precision_score(y_test, y_pred_knn,average='weighted')

0.8193884956943035

In [59]:
recall_score(y_test, y_pred_knn, average='weighted')

0.8172222222222222

In [60]:
f1_score(y_test, y_pred_knn, average='weighted')

0.8180517640100483

In [61]:
#Decision Tree

In [62]:
from sklearn import tree

In [63]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train_lda, y_train)

In [64]:
dt.tree_.node_count

1973

In [65]:
dt.tree_.max_depth

33

In [66]:
y_pred_dt=dt.predict(X_test_lda)

In [67]:
y_pred_dt

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [68]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[435, 134,  26],
       [117, 451,  29],
       [ 37,  37, 534]], dtype=int64)

In [69]:
accuracy_score(y_test, y_pred_dt)

0.7888888888888889

In [70]:
precision_score(y_test, y_pred_dt,average='weighted')

0.7908500201078362

In [71]:
recall_score(y_test, y_pred_dt, average='weighted')

0.7888888888888889

In [72]:
f1_score(y_test, y_pred_dt, average='weighted')

0.7896839986813837

In [73]:
#Random Forest

In [74]:
from sklearn.ensemble import RandomForestClassifier

In [75]:
rf = RandomForestClassifier()
rf.fit(X_train_lda, y_train)

RandomForestClassifier()

In [76]:
y_pred_rf=rf.predict(X_test_lda)

In [77]:
y_pred_rf

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [78]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[456, 117,  22],
       [ 91, 486,  20],
       [ 25,  35, 548]], dtype=int64)

In [79]:
accuracy_score(y_test, y_pred_rf)

0.8277777777777777

In [80]:
precision_score(y_test, y_pred_rf,average='weighted')

0.8299012963787948

In [81]:
recall_score(y_test, y_pred_rf, average='weighted')

0.8277777777777777

In [82]:
f1_score(y_test, y_pred_rf, average='weighted')

0.8283813646919723

In [83]:
#Support Vector Machine

In [84]:
from sklearn.svm import SVC

In [85]:
svm = SVC()
svm.fit(X_train_lda, y_train)

SVC()

In [86]:
y_pred_svm=svm.predict(X_test_lda)

In [87]:
y_pred_svm

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Normal'], dtype=object)

In [88]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[481,  96,  18],
       [ 84, 492,  21],
       [ 26,  29, 553]], dtype=int64)

In [89]:
accuracy_score(y_test, y_pred_svm)

0.8477777777777777

In [90]:
precision_score(y_test, y_pred_svm,average='weighted')

0.849029616087387

In [91]:
recall_score(y_test, y_pred_svm, average='weighted')

0.8477777777777777

In [92]:
f1_score(y_test, y_pred_svm, average='weighted')

0.8482723091424893