In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('C:/Users/Sneha Reddy/OneDrive/Documents/AI-Project/Merged_CSV.csv')

In [3]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [4]:
X

array([[   0,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   2,    0,    0, ...,    1,    1,    0],
       ...,
       [8997,    0,    0, ...,    1,   28,   16],
       [8998,    0,    0, ...,   16,   38,    0],
       [8999,    0,    0, ...,    5,   19,    0]], dtype=int64)

In [5]:
y

array([0, 0, 0, ..., 5, 1, 0], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(7200, 625)

In [9]:
X_test.shape

(1800, 625)

In [10]:
y_train.shape

(7200,)

In [11]:
y_test.shape

(1800,)

In [12]:
X_train

array([[6157,    0,    0, ...,  218,  165,    1],
       [2923,    0,    0, ...,    2,    1,    0],
       [5155,    0,    0, ...,    1,    0,    0],
       ...,
       [4859,    0,    0, ...,    1,    2,    2],
       [3264,    0,    0, ...,    1,    1,    1],
       [2732,    0,    0, ...,    1,    0,    0]], dtype=int64)

In [13]:
X_test

array([[4424,    0,    0, ...,    1,    1,    1],
       [1726,    0,    0, ...,    1,    0,    0],
       [7895,    0,    0, ...,    8,   10,    1],
       ...,
       [7193,    0,    0, ...,    1,    0,    0],
       [6280,    0,    0, ...,    1,    5,    8],
       [4905,    0,    0, ...,    2,    2,    1]], dtype=int64)

In [14]:
y_train

array([4, 0, 0, ..., 4, 1, 0], dtype=int64)

In [15]:
y_test

array([6, 0, 1, ..., 0, 1, 0], dtype=int64)

In [16]:
#Feature Scaling
#Standardize the data
#X_std=(x-mean(x))/std_dev(x)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [19]:
X_train

array([[ 0.64166305, -0.2280515 , -0.02495553, ...,  6.06473378,
         4.41463923, -0.23525444],
       [-0.60548323, -0.2280515 , -0.02495553, ..., -0.30870956,
        -0.31406133, -0.26317965],
       [ 0.25525595, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965],
       ...,
       [ 0.14110774, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.28522779, -0.20732922],
       [-0.47398141, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.31406133, -0.23525444],
       [-0.67913967, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965]])

In [20]:
X_test

array([[-0.02664385, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.31406133, -0.23525444],
       [-1.06708932, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965],
       [ 1.31189812, -0.2280515 , -0.02495553, ..., -0.13166947,
        -0.05455947, -0.23525444],
       ...,
       [ 1.04118177, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965],
       [ 0.68909626, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.19872717, -0.03977792],
       [ 0.15884699, -0.2280515 , -0.02495553, ..., -0.30870956,
        -0.28522779, -0.23525444]])

In [21]:
#LDA for dimensionality reduction

In [22]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [23]:
lda=LDA(n_components=2)

In [24]:
X_train_lda=lda.fit_transform(X_train,y_train)
X_test_lda=lda.transform(X_test)

In [25]:
lda.n_components

2

In [26]:
X_train_lda

array([[-1.72497214,  0.18238204],
       [-1.56076408,  0.70161089],
       [-1.12130389, -0.1546764 ],
       ...,
       [-1.2760718 ,  0.24535494],
       [-0.90754793,  0.59970516],
       [-1.54017475,  0.11177467]])

In [27]:
X_train_lda.shape

(7200, 2)

In [28]:
X_test_lda

array([[-4.15285846, -4.25352301],
       [-1.14729015,  0.58930542],
       [-1.54912764,  0.17523365],
       ...,
       [-1.91807006,  0.45852722],
       [-0.87857902,  0.13493555],
       [-1.3611236 ,  0.58521579]])

In [29]:
X_test_lda.shape

(1800, 2)

In [30]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [31]:
#Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
logreg = LogisticRegression()
logreg.fit(X_train_lda,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [34]:
y_pred_logreg=logreg.predict(X_test_lda)

In [35]:
y_pred_logreg

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[1067,    3,    0, ...,    0,    0,    0],
       [ 266,    9,    1, ...,    0,    0,    0],
       [  96,    6,    0, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [37]:
accuracy_score(y_test, y_pred_logreg)

0.6022222222222222

In [38]:
precision_score(y_test, y_pred_logreg,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4480840475230221

In [39]:
recall_score(y_test, y_pred_logreg, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6022222222222222

In [40]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.4909527686270129

In [41]:
#Naive Bayes

In [42]:
from sklearn.naive_bayes import GaussianNB

In [43]:
nb = GaussianNB()
nb.fit(X_train_lda,y_train)

GaussianNB()

In [44]:
y_pred_nb=nb.predict(X_test_lda)

In [45]:
y_pred_nb

array([9, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[1042,   10,    0, ...,    0,    0,    0],
       [ 256,    9,    0, ...,    0,    0,    0],
       [  85,    7,    0, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [47]:
accuracy_score(y_test, y_pred_nb)

0.5894444444444444

In [48]:
precision_score(y_test, y_pred_nb,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4531826230491157

In [49]:
recall_score(y_test, y_pred_nb, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5894444444444444

In [50]:
f1_score(y_test, y_pred_nb, average='weighted')

0.4969276199300517

In [51]:
#KNN

In [52]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_lda,y_train)

KNeighborsClassifier(n_neighbors=3)

In [54]:
y_pred_knn=knn.predict(X_test_lda)

In [55]:
y_pred_knn

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [56]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[968,  73,  19, ...,   0,   0,   0],
       [220,  44,   9, ...,   0,   0,   0],
       [ 70,  19,   9, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [57]:
accuracy_score(y_test, y_pred_knn)

0.5705555555555556

In [58]:
precision_score(y_test, y_pred_knn,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4734002100930827

In [59]:
recall_score(y_test, y_pred_knn, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5705555555555556

In [60]:
f1_score(y_test, y_pred_knn, average='weighted')

0.5109349809060862

In [61]:
#Decision Tree

In [62]:
from sklearn import tree

In [63]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train_lda, y_train)

In [64]:
dt.tree_.node_count

6459

In [65]:
dt.tree_.max_depth

48

In [66]:
y_pred_dt=dt.predict(X_test_lda)

In [67]:
y_pred_dt

array([7, 1, 0, ..., 0, 0, 1], dtype=int64)

In [68]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[750, 175,  60, ...,   0,   0,   0],
       [147,  64,  26, ...,   0,   0,   0],
       [ 53,  19,  10, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [69]:
accuracy_score(y_test, y_pred_dt)

0.465

In [70]:
precision_score(y_test, y_pred_dt,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4846560453343235

In [71]:
recall_score(y_test, y_pred_dt, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.465

In [72]:
f1_score(y_test, y_pred_dt, average='weighted')

0.47389496885610166

In [73]:
#Random Forest

In [74]:
from sklearn.ensemble import RandomForestClassifier

In [75]:
rf = RandomForestClassifier()
rf.fit(X_train_lda, y_train)

RandomForestClassifier()

In [76]:
y_pred_rf=rf.predict(X_test_lda)

In [77]:
y_pred_rf

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [78]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[943,  64,  21, ...,   0,   0,   0],
       [201,  45,  13, ...,   0,   0,   0],
       [ 66,  16,   6, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [79]:
accuracy_score(y_test, y_pred_rf)

0.5588888888888889

In [80]:
precision_score(y_test, y_pred_rf,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.487206821151357

In [81]:
recall_score(y_test, y_pred_rf, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5588888888888889

In [82]:
f1_score(y_test, y_pred_rf, average='weighted')

0.5140496909639066

In [83]:
#Support Vector Machine

In [84]:
from sklearn.svm import SVC

In [85]:
svm = SVC()
svm.fit(X_train_lda, y_train)

SVC()

In [86]:
y_pred_svm=svm.predict(X_test_lda)

In [87]:
y_pred_svm

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [88]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[1078,    0,    0, ...,    0,    0,    0],
       [ 283,    0,    0, ...,    0,    0,    0],
       [ 105,    0,    0, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    1,    0],
       [   0,    0,    0, ...,    0,    1,    0]], dtype=int64)

In [89]:
accuracy_score(y_test, y_pred_svm)

0.6027777777777777

In [90]:
precision_score(y_test, y_pred_svm,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.38677458644741125

In [91]:
recall_score(y_test, y_pred_svm, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.6027777777777777

In [92]:
f1_score(y_test, y_pred_svm, average='weighted')

0.4707470609378002