In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('C:/Users/Sneha Reddy/OneDrive/Documents/AI-Project/Merged_CSV.csv')

In [3]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [4]:
X

array([[   0,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   2,    0,    0, ...,    1,    1,    0],
       ...,
       [8997,    0,    0, ...,    1,   28,   16],
       [8998,    0,    0, ...,   16,   38,    0],
       [8999,    0,    0, ...,    5,   19,    0]], dtype=int64)

In [5]:
y

array([0, 0, 0, ..., 5, 1, 0], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(7200, 625)

In [9]:
X_test.shape

(1800, 625)

In [10]:
y_train.shape

(7200,)

In [11]:
y_test.shape

(1800,)

In [12]:
X_train

array([[6157,    0,    0, ...,  218,  165,    1],
       [2923,    0,    0, ...,    2,    1,    0],
       [5155,    0,    0, ...,    1,    0,    0],
       ...,
       [4859,    0,    0, ...,    1,    2,    2],
       [3264,    0,    0, ...,    1,    1,    1],
       [2732,    0,    0, ...,    1,    0,    0]], dtype=int64)

In [13]:
X_test

array([[4424,    0,    0, ...,    1,    1,    1],
       [1726,    0,    0, ...,    1,    0,    0],
       [7895,    0,    0, ...,    8,   10,    1],
       ...,
       [7193,    0,    0, ...,    1,    0,    0],
       [6280,    0,    0, ...,    1,    5,    8],
       [4905,    0,    0, ...,    2,    2,    1]], dtype=int64)

In [14]:
y_train

array([4, 0, 0, ..., 4, 1, 0], dtype=int64)

In [15]:
y_test

array([6, 0, 1, ..., 0, 1, 0], dtype=int64)

In [16]:
#Feature Scaling
#Standardize the data
#X_std=(x-mean(x))/std_dev(x)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [19]:
X_train

array([[ 0.64166305, -0.2280515 , -0.02495553, ...,  6.06473378,
         4.41463923, -0.23525444],
       [-0.60548323, -0.2280515 , -0.02495553, ..., -0.30870956,
        -0.31406133, -0.26317965],
       [ 0.25525595, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965],
       ...,
       [ 0.14110774, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.28522779, -0.20732922],
       [-0.47398141, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.31406133, -0.23525444],
       [-0.67913967, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965]])

In [20]:
X_test

array([[-0.02664385, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.31406133, -0.23525444],
       [-1.06708932, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965],
       [ 1.31189812, -0.2280515 , -0.02495553, ..., -0.13166947,
        -0.05455947, -0.23525444],
       ...,
       [ 1.04118177, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.34289487, -0.26317965],
       [ 0.68909626, -0.2280515 , -0.02495553, ..., -0.33821625,
        -0.19872717, -0.03977792],
       [ 0.15884699, -0.2280515 , -0.02495553, ..., -0.30870956,
        -0.28522779, -0.23525444]])

In [21]:
#PCA for dimensionality reduction

In [22]:
from sklearn.decomposition import PCA

In [23]:
pca=PCA(n_components=0.90)

In [24]:
X_train_pca=pca.fit_transform(X_train)
X_test_pca=pca.transform(X_test)

In [25]:
pca.n_components_

120

In [26]:
X_train_pca

array([[ 15.39285241,  10.82675644,   5.08847794, ...,   0.77712727,
          0.6348382 ,  -1.17066908],
       [ -1.52553293,   5.7709148 ,  -2.43585214, ...,   0.06469077,
          0.84920983,   2.20116769],
       [ -5.37609552, -13.75106354,  10.98344291, ...,   0.24065042,
         -0.43163877,   0.31715457],
       ...,
       [ -6.06909116,   1.09476233,  -4.63748537, ...,   1.31522474,
          0.72775849,  -0.17294694],
       [ -4.15392787, -11.33224494,   5.93906469, ...,  -0.25392363,
          0.13483814,  -0.43086679],
       [ -9.99619751,   3.54070809,   5.14403242, ...,  -0.81937241,
         -0.35100027,  -0.82068   ]])

In [27]:
X_train_pca.shape

(7200, 120)

In [28]:
X_test_pca.shape

(1800, 120)

In [29]:
explained_var=pca.explained_variance_ratio_
explained_var

array([0.09710361, 0.06752801, 0.06028836, 0.05498589, 0.04806642,
       0.03976716, 0.02776875, 0.02207643, 0.02151275, 0.01750491,
       0.01724764, 0.01569889, 0.01460552, 0.01363742, 0.0129041 ,
       0.01266636, 0.01121037, 0.01088293, 0.0100673 , 0.0100353 ,
       0.00950847, 0.00917084, 0.00849864, 0.00839781, 0.00804228,
       0.00758217, 0.00732093, 0.00712381, 0.00685811, 0.00666091,
       0.00638368, 0.00617798, 0.00590151, 0.00580835, 0.00554143,
       0.00542235, 0.00521894, 0.00506353, 0.00501024, 0.00499314,
       0.00456998, 0.0044386 , 0.00434882, 0.00422738, 0.00419071,
       0.00396588, 0.00394568, 0.00385722, 0.00375604, 0.003708  ,
       0.00363593, 0.00351429, 0.00339233, 0.00335507, 0.00323954,
       0.0031903 , 0.00311072, 0.0030305 , 0.00299833, 0.00291374,
       0.00286934, 0.00278674, 0.00275634, 0.00271875, 0.00267624,
       0.0026123 , 0.00257882, 0.00249719, 0.00247457, 0.00242223,
       0.00236569, 0.00233953, 0.00230782, 0.00226074, 0.00222

In [30]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [31]:
#Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
logreg = LogisticRegression()
logreg.fit(X_train_pca,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [34]:
y_pred_logreg=logreg.predict(X_test_pca)

In [35]:
y_pred_logreg

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [36]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[1012,   42,    5, ...,    0,    0,    0],
       [ 223,   33,    7, ...,    0,    0,    0],
       [  77,   10,    1, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [37]:
accuracy_score(y_test, y_pred_logreg)

0.5855555555555556

In [38]:
precision_score(y_test, y_pred_logreg,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.47683040407867994

In [39]:
recall_score(y_test, y_pred_logreg, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5855555555555556

In [40]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.5127026245888378

In [41]:
#Naive Bayes

In [42]:
from sklearn.naive_bayes import GaussianNB

In [43]:
nb = GaussianNB()
nb.fit(X_train_pca,y_train)

GaussianNB()

In [44]:
y_pred_nb=nb.predict(X_test_pca)

In [45]:
y_pred_nb

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [46]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[911,  52,  16, ...,   0,   0,   0],
       [202,  19,   9, ...,   0,   0,   0],
       [ 65,   8,   3, ...,   0,   0,   0],
       ...,
       [  0,   1,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [47]:
accuracy_score(y_test, y_pred_nb)

0.5211111111111111

In [48]:
precision_score(y_test, y_pred_nb,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.45256208112764457

In [49]:
recall_score(y_test, y_pred_nb, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5211111111111111

In [50]:
f1_score(y_test, y_pred_nb, average='weighted')

0.4779595328924855

In [51]:
#KNN

In [52]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_pca,y_train)

KNeighborsClassifier(n_neighbors=3)

In [54]:
y_pred_knn=knn.predict(X_test_pca)

In [55]:
y_pred_knn

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [56]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[959,  93,  18, ...,   0,   0,   0],
       [210,  57,   9, ...,   0,   0,   0],
       [ 65,  29,   7, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [57]:
accuracy_score(y_test, y_pred_knn)

0.5716666666666667

In [58]:
precision_score(y_test, y_pred_knn,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4666558163681077

In [59]:
recall_score(y_test, y_pred_knn, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.5716666666666667

In [60]:
f1_score(y_test, y_pred_knn, average='weighted')

0.509133626377793

In [61]:
#Decision Tree

In [62]:
from sklearn import tree

In [63]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train_pca, y_train)

In [64]:
dt.tree_.node_count

3787

In [65]:
dt.tree_.max_depth

63

In [66]:
y_pred_dt=dt.predict(X_test_pca)

In [67]:
y_pred_dt

array([0, 2, 1, ..., 0, 1, 1], dtype=int64)

In [68]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[736, 173,  68, ...,   0,   0,   0],
       [152,  56,  21, ...,   0,   0,   0],
       [ 52,  12,   9, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [69]:
accuracy_score(y_test, y_pred_dt)

0.4483333333333333

In [70]:
precision_score(y_test, y_pred_dt,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4631905354522287

In [71]:
recall_score(y_test, y_pred_dt, average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4483333333333333

In [72]:
f1_score(y_test, y_pred_dt, average='weighted')

0.455454095755508

In [73]:
#Random Forest

In [74]:
from sklearn.ensemble import RandomForestClassifier

In [75]:
rf = RandomForestClassifier()
rf.fit(X_train_pca, y_train)

RandomForestClassifier()

In [76]:
y_pred_rf=rf.predict(X_test_pca)

In [77]:
y_pred_rf

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [78]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[1069,   11,    1, ...,    0,    0,    0],
       [ 268,   15,    0, ...,    0,    0,    0],
       [  99,    4,    1, ...,    0,    0,    0],
       ...,
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [79]:
accuracy_score(y_test, y_pred_rf)

0.6038888888888889

In [80]:
precision_score(y_test, y_pred_rf,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.43177479022412046

In [81]:
recall_score(y_test, y_pred_rf, average='weighted')

0.6038888888888889

In [82]:
f1_score(y_test, y_pred_rf, average='weighted')

0.47517862930836485

In [83]:
#Support Vector Machine

In [84]:
from sklearn.svm import SVC

In [85]:
svm = SVC()
svm.fit(X_train_pca, y_train)

SVC()

In [86]:
y_pred_svm=svm.predict(X_test_pca)

In [87]:
y_pred_svm

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [88]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[1068,   12,    1, ...,    0,    0,    0],
       [ 265,   18,    0, ...,    0,    0,    0],
       [  95,    7,    3, ...,    0,    0,    0],
       ...,
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [89]:
accuracy_score(y_test, y_pred_svm)

0.605

In [90]:
precision_score(y_test, y_pred_svm,average='weighted')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.4402911604766863

In [91]:
recall_score(y_test, y_pred_svm, average='weighted')

0.605

In [92]:
f1_score(y_test, y_pred_svm, average='weighted')

0.47728186908725106