In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('C:/Users/Sneha Reddy/OneDrive/Documents/AI-Project/Merged_Segmented_CSV.csv')

In [3]:
X=dataset.iloc[:,0:625].values
y=dataset.iloc[:,625].values

In [4]:
X

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  1,  0,  0],
       ...,
       [ 0,  0,  0, ..., 28, 16,  5],
       [ 0,  0,  0, ..., 38,  0,  1],
       [ 0,  0,  0, ..., 19,  0,  0]], dtype=int64)

In [5]:
y

array(['Normal', 'Normal', 'Normal', ..., 'Pneumonia', 'Pneumonia',
       'Pneumonia'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(7200, 625)

In [9]:
X_test.shape

(1800, 625)

In [10]:
y_train.shape

(7200,)

In [11]:
y_test.shape

(1800,)

In [12]:
X_train

array([[  0,   0,   0, ..., 165,   1,   4],
       [  0,   0,   0, ...,   1,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   2,   2,   4],
       [  0,   0,   0, ...,   1,   1,   1],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=int64)

In [13]:
X_test

array([[ 0,  0,  0, ...,  1,  1,  6],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., 10,  1,  1],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  5,  8,  1],
       [ 0,  0,  0, ...,  2,  1,  0]], dtype=int64)

In [14]:
y_train

array(['Pneumonia', 'Normal', 'Other', ..., 'Other', 'Other', 'Normal'],
      dtype=object)

In [15]:
y_test

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [16]:
#Feature Scaling
#Standardize the data
#X_std=(x-mean(x))/std_dev(x)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [19]:
X_train

array([[-0.2280515 , -0.02495553, -0.04092578, ...,  4.41463923,
        -0.23525444, -0.0568118 ],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.31406133,
        -0.26317965, -0.23354325],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325],
       ...,
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.28522779,
        -0.20732922, -0.0568118 ],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.31406133,
        -0.23525444, -0.18936039],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325]])

In [20]:
X_test

array([[-0.2280515 , -0.02495553, -0.04092578, ..., -0.31406133,
        -0.23525444,  0.03155393],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.05455947,
        -0.23525444, -0.18936039],
       ...,
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.34289487,
        -0.26317965, -0.23354325],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.19872717,
        -0.03977792, -0.18936039],
       [-0.2280515 , -0.02495553, -0.04092578, ..., -0.28522779,
        -0.23525444, -0.23354325]])

In [21]:
#PCA for dimensionality reduction

In [22]:
from sklearn.decomposition import PCA

In [23]:
pca=PCA(n_components=0.90)

In [24]:
X_train_pca=pca.fit_transform(X_train)
X_test_pca=pca.transform(X_test)

In [25]:
pca.n_components_

120

In [26]:
X_train_pca

array([[ 1.53445409e+01,  1.09679545e+01,  5.01490159e+00, ...,
         4.06016885e-01,  6.76217421e-01,  1.08192645e+00],
       [-1.49978574e+00,  5.72814271e+00, -2.54212636e+00, ...,
        -3.08125552e-01,  5.24729297e-01, -2.22159133e+00],
       [-5.43345791e+00, -1.35303506e+01,  1.12344337e+01, ...,
         9.71905848e-02, -5.41821456e-01, -2.00436823e-01],
       ...,
       [-6.07514458e+00,  1.04997404e+00, -4.56785383e+00, ...,
        -1.11165156e+00,  7.57568946e-01, -7.67976517e-03],
       [-4.15097625e+00, -1.11921582e+01,  6.23779197e+00, ...,
         6.22599507e-01,  2.24909655e-01,  3.08795204e-01],
       [-9.95841385e+00,  3.54008028e+00,  4.89750650e+00, ...,
         5.60667092e-01, -1.92733867e-01,  7.79354906e-01]])

In [27]:
X_train_pca.shape

(7200, 120)

In [28]:
X_test_pca.shape

(1800, 120)

In [29]:
explained_var=pca.explained_variance_ratio_
explained_var

array([0.09679834, 0.06763976, 0.06042077, 0.05498501, 0.04815272,
       0.03991901, 0.02773235, 0.02205989, 0.02155017, 0.01748464,
       0.01724764, 0.0157157 , 0.01467679, 0.01360967, 0.01291569,
       0.01265776, 0.01117808, 0.01087864, 0.01006923, 0.01002525,
       0.00951105, 0.00917254, 0.00853271, 0.00839718, 0.00806173,
       0.0075892 , 0.00731476, 0.00712652, 0.00687646, 0.00669013,
       0.00638308, 0.0061789 , 0.00589133, 0.00580655, 0.00554063,
       0.00541985, 0.00521883, 0.0050644 , 0.00500984, 0.00499645,
       0.004571  , 0.00443862, 0.00434851, 0.0042233 , 0.0041896 ,
       0.00396538, 0.00395261, 0.00385618, 0.0037635 , 0.00370797,
       0.0036448 , 0.00351566, 0.003409  , 0.00335485, 0.00324107,
       0.0031907 , 0.00310547, 0.00303762, 0.00299797, 0.00291553,
       0.0028668 , 0.00278929, 0.00275536, 0.00272206, 0.00267626,
       0.00262266, 0.00257943, 0.00249062, 0.0024742 , 0.0024195 ,
       0.00236504, 0.00233431, 0.00231786, 0.00226629, 0.00222

In [30]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [31]:
#Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
logreg = LogisticRegression()
logreg.fit(X_train_pca,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [34]:
y_pred_logreg=logreg.predict(X_test_pca)

In [35]:
y_pred_logreg

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Normal'], dtype=object)

In [36]:
conf_matrix = confusion_matrix(y_test,y_pred_logreg)
conf_matrix

array([[534,  51,  10],
       [ 58, 524,  15],
       [ 16,  23, 569]], dtype=int64)

In [37]:
accuracy_score(y_test, y_pred_logreg)

0.9038888888888889

In [38]:
precision_score(y_test, y_pred_logreg,average='weighted')

0.9045093094845987

In [39]:
recall_score(y_test, y_pred_logreg, average='weighted')

0.9038888888888889

In [40]:
f1_score(y_test, y_pred_logreg, average='weighted')

0.9041212336464683

In [41]:
#Naive Bayes

In [42]:
from sklearn.naive_bayes import GaussianNB

In [43]:
nb = GaussianNB()
nb.fit(X_train_pca,y_train)

GaussianNB()

In [44]:
y_pred_nb=nb.predict(X_test_pca)

In [45]:
y_pred_nb

array(['Other', 'Normal', 'Normal', ..., 'Normal', 'Pneumonia', 'Normal'],
      dtype='<U9')

In [46]:
conf_matrix = confusion_matrix(y_test,y_pred_nb)
conf_matrix

array([[504,  25,  66],
       [370, 132,  95],
       [254,  32, 322]], dtype=int64)

In [47]:
accuracy_score(y_test, y_pred_nb)

0.5322222222222223

In [48]:
precision_score(y_test, y_pred_nb,average='weighted')

0.6045204322863896

In [49]:
recall_score(y_test, y_pred_nb, average='weighted')

0.5322222222222223

In [50]:
f1_score(y_test, y_pred_nb, average='weighted')

0.5041679903680333

In [51]:
#KNN

In [52]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_pca,y_train)

KNeighborsClassifier(n_neighbors=3)

In [54]:
y_pred_knn=knn.predict(X_test_pca)

In [55]:
y_pred_knn

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Other'], dtype=object)

In [56]:
conf_matrix = confusion_matrix(y_test,y_pred_knn)
conf_matrix

array([[424, 151,  20],
       [123, 457,  17],
       [ 37,  21, 550]], dtype=int64)

In [57]:
accuracy_score(y_test, y_pred_knn)

0.795

In [58]:
precision_score(y_test, y_pred_knn,average='weighted')

0.797451677277064

In [59]:
recall_score(y_test, y_pred_knn, average='weighted')

0.795

In [60]:
f1_score(y_test, y_pred_knn, average='weighted')

0.7959405249627469

In [61]:
#Decision Tree

In [62]:
from sklearn import tree

In [63]:
dt = tree.DecisionTreeClassifier()
dt=dt.fit(X_train_pca, y_train)

In [64]:
dt.tree_.node_count

1495

In [65]:
dt.tree_.max_depth

30

In [66]:
y_pred_dt=dt.predict(X_test_pca)

In [67]:
y_pred_dt

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Normal'], dtype=object)

In [68]:
conf_matrix = confusion_matrix(y_test,y_pred_dt)
conf_matrix

array([[378, 151,  66],
       [166, 386,  45],
       [ 65,  52, 491]], dtype=int64)

In [69]:
accuracy_score(y_test, y_pred_dt)

0.6972222222222222

In [70]:
precision_score(y_test, y_pred_dt,average='weighted')

0.6980260093975184

In [71]:
recall_score(y_test, y_pred_dt, average='weighted')

0.6972222222222222

In [72]:
f1_score(y_test, y_pred_dt, average='weighted')

0.6975794843644456

In [73]:
#Random Forest

In [74]:
from sklearn.ensemble import RandomForestClassifier

In [75]:
rf = RandomForestClassifier()
rf.fit(X_train_pca, y_train)

RandomForestClassifier()

In [76]:
y_pred_rf=rf.predict(X_test_pca)

In [77]:
y_pred_rf

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Normal'], dtype=object)

In [78]:
conf_matrix = confusion_matrix(y_test,y_pred_rf)
conf_matrix

array([[407, 149,  39],
       [ 88, 472,  37],
       [ 28,  15, 565]], dtype=int64)

In [79]:
accuracy_score(y_test, y_pred_rf)

0.8022222222222222

In [80]:
precision_score(y_test, y_pred_rf,average='weighted')

0.801111018340706

In [81]:
recall_score(y_test, y_pred_rf, average='weighted')

0.8022222222222222

In [82]:
f1_score(y_test, y_pred_rf, average='weighted')

0.8001965047173164

In [83]:
#Support Vector Machine

In [84]:
from sklearn.svm import SVC

In [85]:
svm = SVC()
svm.fit(X_train_pca, y_train)

SVC()

In [86]:
y_pred_svm=svm.predict(X_test_pca)

In [87]:
y_pred_svm

array(['Other', 'Normal', 'Pneumonia', ..., 'Pneumonia', 'Pneumonia',
       'Normal'], dtype=object)

In [88]:
conf_matrix = confusion_matrix(y_test,y_pred_svm)
conf_matrix

array([[502,  84,   9],
       [ 80, 501,  16],
       [ 12,   9, 587]], dtype=int64)

In [89]:
accuracy_score(y_test, y_pred_svm)

0.8833333333333333

In [90]:
precision_score(y_test, y_pred_svm,average='weighted')

0.8830771219823507

In [91]:
recall_score(y_test, y_pred_svm, average='weighted')

0.8833333333333333

In [92]:
f1_score(y_test, y_pred_svm, average='weighted')

0.8831997656133123